### ISSUE TITLE
Watchdog feature

### ISSUE THREAD

**Issue by theyosh** [alec-pinson/TerrariumPI#27]
Sometimes my software gets stuck and needs a restart. How can we do this with Docker?

You can detect if it is stuck, when the logfile is not update. Or when you do not receive a `sd_notify` for 2 minutes (should be every 30 seconds) though systemd.

I have seen that there are watchdog docker images that can act on the image health state. But I have not looked into that.

**Comment by alec-pinson** [comment]
We can add a health check like this for example

https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

**Comment by theyosh** [comment]
Hmm, I found a different approach which suite me better: https://github.com/theyosh/TerrariumPI/blob/4.x.y.z/contrib/docker_health.py

The file motd.sh should be updated every 30 seconds. If it is older then 2 minutes, the container should be marked as unhealthy. I am now creating a new image to test this.

`HEALTHCHECK --interval=30s --timeout=5s --start-period=120s CMD python contrib/docker_health.py`

in the Dockerfile.

And you need to add an extra container to the docker-compose.yaml file to add the healthchecker container... which one is mostly used?

**Comment by alec-pinson** [comment]
1 thing I probably should have mentioned is if your app exits then it should automatically restart the container

**Comment by alec-pinson** [comment]
> And you need to add an extra container to the docker-compose.yaml file to add the healthchecker container... which one is mostly used?

hmm maybe another container is abit overkill for this, whats guna monitor the monitoring container after that? 😄

**Comment by theyosh** [comment]
You mean the main process?

**Comment by theyosh** [comment]
> > And you need to add an extra container to the docker-compose.yaml file to add the healthchecker container... which one is mostly used?
> 
> hmm maybe another container is abit overkill for this, whats guna monitor the monitoring container after that? smile

It is needed, as the software can hang on broken bluetooth sensors... So I need to make sure, that when it is hanging, it restarts. And now I do that using the systemd mechanism for it. So on a normal Pi it is taken care for me by the OS. And I have 2 to 3 restarts a day on production systems. And I have made my software in such way, that it can handle this, and you will not notice it.

Therefore, this should also work in Docker. Else I have to tell people how to fix this, where if you run it natively, it is fixed for you.

Also, how to make the Docker restart when the Python code crashes... Here I also rely on systemd, which is fixing that for me.

**Comment by alec-pinson** [comment]
if app crashes and exits with non-zero code it will restart
if app exits with 0 code it will also restart
if pi crashes and reboots it will the container will restart

**Comment by alec-pinson** [comment]
However if your app hangs and doesn't exit there will be no restart unless there's a healthcheck

**Comment by theyosh** [comment]
is the healthcheck enough? Does docker check it self? Or is there an external system needed to readout the state, and give a restart command.

**Comment by alec-pinson** [comment]
Yea I think adding the HEALTHCHECK line into Dockerfile should be enough. Docker does the rest of the magic.

**Comment by alec-pinson** [comment]
if you do `docker ps` after adding the health check you should see
![image](https://user-images.githubusercontent.com/30310787/142465160-8abea7b9-6df8-41c7-b5af-acca314a609a.png)

**Comment by theyosh** [comment]
> Yea I think adding the HEALTHCHECK line into Dockerfile should be enough. Docker does the rest of the magic.
Ah, now it is clear...  because I have another pi running 10 containers, which one is https://github.com/willfarrell/docker-autoheal
And that is needed to restart unhealthy containers. So I did not know if Docker can do it self, or if you need an extra image for that

**Comment by alec-pinson** [comment]
So I tested and the container went unhealthy

![image](https://user-images.githubusercontent.com/30310787/142467647-bd3a76ee-9a40-4045-8fd1-c41f6e6cabd7.png)

i copied `motd.sh` to `old.sh` and editied `docker_health.py` to look at `old.sh` instead

However... it seems to just stay unhealthy, I thought it would automatically restart, looks like you're right

**Comment by alec-pinson** [comment]
Sends `SIGINT` waits 60 seconds and sends `KILL`
```Dockerfile
HEALTHCHECK --interval=30s --timeout=5s --start-period=120s CMD python contrib/docker_health.py || kill -s 2 -1 && (sleep 60; kill -s 9 -1)
```

Also add `init: true`
```yaml
    stop_grace_period: 1m
    stop_signal: SIGINT
    init: true
```

**Comment by alec-pinson** [comment]
That's not properly tested by the way, don't have time at the moment.

**Comment by theyosh** [comment]
I can test it. Do I understand, that when the exit value of the python script is 1, it will try to stop and then kill it? That is the part after the `or` statement. Right? And then Docker will kick in again.

**Comment by alec-pinson** [comment]
here this works 
https://github.com/alec-pinson/TerrariumPI/pull/28

**Comment by alec-pinson** [comment]
Hmm maybe a bug I think it restarts before `motd.sh` gets produced

I gotta go, i'll leave it with you hopefully you can get it working :)

**Comment by alec-pinson** [comment]
> I can test it. Do I understand, that when the exit value of the python script is 1, it will try to stop and then kill it? That is the part after the `or` statement. Right? And then Docker will kick in again.

if your main python script exits `exec /opt/venv/bin/python /TerrariumPI/terrariumPI.py` the docker container should restart

**Comment by theyosh** [comment]
So, that was not that easy. Turns out, that files created inside the docker container will NOT be removed with a docker restart. So that introduced a lot of issues after a restart. So I had to change the run.sh file

```
# Clear after restart
if [ -f /var/run/pigpio.pid ]; then
  rm /var/run/pigpio.pid
fi
# run localhost socket only
pigpiod -l

# Remove the restart file from last unhealty status
if [ -f .restart ]; then
  rm .restart
fi

# Clear after restart
if [ -f motd.sh ]; then
  rm motd.sh
fi

# No reboot required, Pi must already be fully configured, start TP
exec /opt/venv/bin/python /TerrariumPI/terrariumPI.py
```

Update the Dockerfile healthcheck: `HEALTHCHECK --interval=120s --timeout=5s --start-period=120s CMD python contrib/docker_health.py` as when it restarts, it does not use the start-period of 120 seconds. So it keeps restarting every 30 seconds, as the startup takes more time... as the `motd.sh` is not removed with the restart.

And not sure if this is handy, but I changed the Dockerfile a bit:

```
# Build for raspberry pi
# docker buildx build --platform linux/arm/v7 --progress=plain -t theyosh/terrariumpi:4.0.0 -f Dockerfile --push .

# build sispmctl 4.9
FROM gcc:9.4.0-buster as sispmctl_builder
RUN apt-get update && apt-get install -y --no-install-recommends libusb-dev && \
  wget https://sourceforge.net/projects/sispmctl/files/sispmctl/sispmctl-4.9/sispmctl-4.9.tar.gz/download -O sispmctl-4.9.tar.gz && \
  tar zxvf sispmctl-4.9.tar.gz && \
  cd sispmctl-4.9/ && \
  ./configure && \
  make && \
  make install

# python builder, help keep image small
FROM python:3.8-buster as builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends gnupg ca-certificates && \
  echo "deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi" > /etc/apt/sources.list.d/raspberrypi.list && \
  echo "deb http://archive.raspberrypi.org/debian/ buster main" >> /etc/apt/sources.list.d/raspberrypi.list && \
  echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9165938D90FDDD2E 82B129927FA3303E 7EA0A9C3F273FCD8 && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get update && \
  apt-get install -y --no-install-recommends git libxslt1.1 libglib2.0-dev && \
  apt-get install -y --no-install-recommends python3-opencv libftdi1 libasound-dev
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
# rpi.gpio - https://askubuntu.com/questions/1290037/error-while-installing-rpi-gpio-as-error-command-errored-out-with-exit-status
ENV CFLAGS=-fcommon
# cryptography - https://stackoverflow.com/questions/66118337/how-to-get-rid-of-cryptography-build-error
ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1
# These two environment variables prevent __pycache__/ files.
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
RUN pip install --upgrade pip && pip install wheel
COPY requirements.txt .
# requirements are slightly different for docker
RUN sed -i 's/cryptography/cryptography==3.4.6/g' requirements.txt && \
  sed -i 's/opencv-python-headless/# opencv-python-headless/g' requirements.txt && \
  echo "numpy" >> requirements.txt && \
  pip install -r requirements.txt
WORKDIR /TerrariumPI
# we previously copied .git and then did git submodule init and submodule update, however as .git dir changes all the time it invalidates docker cache
RUN mkdir 3rdparty && cd 3rdparty && \
  git clone https://github.com/SequentMicrosystems/4relay-rpi.git && git -C "4relay-rpi" checkout "09a44bfbde18791750534ba204e1dfc7506a7eb2" && \
  git clone https://github.com/PiSupply/Bright-Pi.git && git -C "Bright-Pi" checkout "eccfbbb1221c4966cd337126bedcbb8bb03c3c71" && \
  git clone https://github.com/ageir/chirp-rpi.git && git -C "chirp-rpi" checkout "6e411d6c382d5e43ee1fd269ec4de6a316893407" && \
  git clone https://github.com/perryflynn/energenie-connect0r.git && git -C "energenie-connect0r" checkout "12ca24ab9d60cf4ede331de9a6817c3d64227ea0" && \
  git clone https://github.com/SequentMicrosystems/relay8-rpi.git && git -C "relay8-rpi" checkout "5083730e415ee91fa4785e228f02a36e8bbaa717"
RUN mkdir -p static/assets/plguins && cd static/assets/plguins && \
  git clone https://github.com/fancyapps/fancybox.git && git -C "fancybox" checkout "eea1345256ded510ed9fae1e415aec2a7bb9620d" && \
  git clone https://github.com/mapshakers/leaflet-icon-pulse.git && git -C "leaflet-icon-pulse" checkout "f57da1e45f6d00f340f429a75a39324cad141061" && \
  git clone https://github.com/ebrelsford/Leaflet.loading.git && git -C "Leaflet.loading" checkout "7b22aff19a5a8fa9534fb2dcd48e06c6dc84b2ed"

# remove git dir from code copy to help keep image smaller
FROM bash as sourcecode
WORKDIR /TerrariumPI
COPY . .
RUN rm -rf .git

# actual image
FROM python:3.8-slim-buster
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends gnupg ca-certificates && \
  echo "deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi" > /etc/apt/sources.list.d/raspberrypi.list && \
  echo "deb http://archive.raspberrypi.org/debian/ buster main" >> /etc/apt/sources.list.d/raspberrypi.list && \
  echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9165938D90FDDD2E 82B129927FA3303E 7EA0A9C3F273FCD8 && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get update && \
  apt-get install -y --no-install-recommends sudo pigpio ffmpeg libxslt1.1 && \
  apt-get install -y --no-install-recommends python3-opencv libftdi1 && \
  mkdir -p /usr/share/man/man1 && apt-get install -y --no-install-recommends openjdk-11-jre-headless && \
  apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
COPY --from=sispmctl_builder /usr/local/lib/libsispmctl* /usr/local/lib/.
COPY --from=sispmctl_builder /usr/local/bin/sispmctl /usr/local/bin/sispmctl
RUN rm /usr/local/lib/libsispmctl.so /usr/local/lib/libsispmctl.so.0 && ln -s /usr/local/lib/libsispmctl.so.0.2.1 /usr/local/lib/libsispmctl.so && ln -s /usr/local/lib/libsispmctl.so.0.2.1 /usr/local/lib/libsispmctl.so.0 && \
  ldconfig
ENV PATH="/opt/venv/bin:$PATH"
COPY --from=builder /opt/venv /opt/venv
RUN ln -s /usr/lib/python3/dist-packages/cv2.cpython-37m-arm-linux-gnueabihf.so /opt/venv/lib/python3.8/site-packages/cv2.so && \
  mv /usr/lib/python3.7/gettext.py /usr/local/lib/python3.8/gettext.py && \
  rm -rf /usr/lib/python3/dist-packages/numpy /usr/lib/python3/dist-packages/numpy-1.16.2.egg-info
WORKDIR /TerrariumPI
COPY --from=builder /TerrariumPI/ /TerrariumPI/.
COPY --from=sourcecode /TerrariumPI /TerrariumPI

HEALTHCHECK --interval=120s --timeout=5s --start-period=120s CMD python contrib/docker_health.py

ENTRYPOINT ["/bin/bash", "/TerrariumPI/run.sh"]
```

Added :
```
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
```

And changed the python version so we have the latest 3.8.X version. This produces now: https://hub.docker.com/layers/178197102/theyosh/terrariumpi/test-5/images/sha256-4909f84eaa6d63566e6c8db4a856a73f1f86c737e3cf975a6f9b94d03c85f1ab?context=repo

**Comment by theyosh** [comment]
And now pigpiod will not start and give a bunch of errors.... So, at this time, I am getting more and more frustrated...

**Comment by theyosh** [comment]
Version 7 is being tested: https://hub.docker.com/r/theyosh/terrariumpi/tags

**Comment by alec-pinson** [comment]
Hi sorry not had time to look at this but I just read this

![image](https://user-images.githubusercontent.com/30310787/142604691-43df2c64-7d17-443e-8611-a773404d4732.png)


![image](https://user-images.githubusercontent.com/30310787/142604715-5b7854ed-241d-4953-baeb-6cd89d13f402.png)

**Comment by alec-pinson** [comment]
restarting a container should always reset whatever is in the container to whatever is in the image... unless files are stored on a volume

**Comment by theyosh** [comment]
Due to the use of `init:` in the docker-compose.yaml file we need version 3.7 So I am using that.

start_period only works the first time... not when it become unhealthy and restarts... Or the motd.sh file is not removed after restart. As also the file `/var/run/pigpio.pid` in the docker stays, which makes pigpiod not starting up after a restart. And therefore I conclude that some files are surviving a restart.

But at this moment, I have had bit enough for now :). So if you take the above Dockerfile and run.sh in your version then I think we are close. For now, the health check is what it is... I think it works now.

Version 10 is now my latest test, which is a bit smaller in size and fixes some restart issues I encountered: https://hub.docker.com/r/theyosh/terrariumpi/tags

**Comment by alec-pinson** [comment]
Can you push your changes to this branch?
https://github.com/alec-pinson/TerrariumPI/tree/healthcheck

**Comment by theyosh** [comment]
Done https://github.com/alec-pinson/TerrariumPI/commit/840437930075182b3d4d543e97ebeba85659ba8b

**Comment by alec-pinson** [comment]
Weird that when it restarts it restores everything, I thought it would just be a fresh container..

**Comment by alec-pinson** [comment]
Maybe this could be an easy fix?
https://github.com/alec-pinson/TerrariumPI/commit/766a47e30eda6420d09ff296639243d4bcf42a89

Basically stop using HEALTHCHECK all together and make our own version...

**Comment by theyosh** [comment]
Hmm, something did a restart :)
```
CONTAINER ID   IMAGE                         COMMAND                  CREATED        STATUS                    PORTS     NAMES
0390525b3277   theyosh/terrariumpi:test-12   "/bin/bash /Terrariu…"   11 hours ago   Up 51 minutes (healthy)             terrariumpi_terrariumpi_1
```
And it wasn't me :P So it looks like it does work...

**Comment by theyosh** [comment]
Yup, here are the logs:

```
2021-11-20 23:00:08,938 - ERROR   - hardware.sensor       - Sensor DHT22 sensor temperature named 'BrokenDHTTemp' at address '11' has exception: DHT22 sensor on GPIO 17 has not responded in 0.5 seconds. Check sensor connection.
2021-11-20 23:03:16,488 - INFO    - terrariumEngine       - Stopping TerrariumPI 4.0.0 after running for 6:58:08 ...
2021-11-20 23:03:16,491 - INFO    - terrariumEngine       - Stopped log tailing.
2021-11-20 23:04:30,126 - INFO    - terrariumEngine       - Starting TerrariumPI 4.0.0 ...
2021-11-20 23:04:30,207 - INFO    - terrariumEngine       - Loaded 29 settings in 0.08 seconds.
```

So something is hanging around 23:00:00 hours, and lock more then 120 seconds, and my health check does force restart.

I can't see what caused the hanging, but I am already happy that it did work. So, I think it is good enough.

**Comment by theyosh** [comment]
So, I think we should start merging...
