### ISSUE TITLE
Logging to memory/flushing to disk

### ISSUE THREAD

**Issue by alec-pinson** [alec-pinson/TerrariumPI#3]
## As per this https://github.com/theyosh/TerrariumPI/pull/626#issuecomment-967460773

> Then I have a special setup for logging. As it does lot of writing. I write it to memory, and once a day it will be rotated at disk. This way, I have reduced the writing on the SD a lot. https://github.com/theyosh/TerrariumPI/blob/4.x.y.z/install.sh#L312-L318
> Is this possible with Docker? If not, then I think we need to add a remark about this. That the SD can wear down a bit faster.

**Comment by alec-pinson** [comment]
I'm hooping that this already works but I will check to confirm.

- [ ] check logging + rotation

**Comment by theyosh** [comment]
Nope, not working correctly. My installer does this during installation. So the Dockerfile should create symlinks somehow.

https://github.com/alec-pinson/TerrariumPI/blob/4.x.y.z/install.sh#L314

Now I have 'normal' files in the log folder, which should be symlinks.

But this is not a major issue, as the logging is working, but it generate more write actions to the SD card. So less prio for this.

**Comment by alec-pinson** [comment]
Woops there was a typing mistake by me which I've corrected. I've also added the symlinks will create a PR shortly
