### ISSUE TITLE
fix/test bluetooth

### ISSUE THREAD

**Issue by alec-pinson** [alec-pinson/TerrariumPI#4]
## As per this https://github.com/theyosh/TerrariumPI/pull/626#issuecomment-967460773

> And I expect Bluetooth not to be working which we do need. https://github.com/theyosh/TerrariumPI/blob/4.x.y.z/install.sh#L282 here I set some special rights to a certain file so a normal user can run it. Else I need root rights to use Bluetooth.

**Comment by alec-pinson** [comment]
So with docker there are a few different options you can pass when starting the container.

---

> --privileged - Privileged containers in Docker are containers that have all of the root capabilities of a host machine

Using this option is classed as bad practice but I have used it for now rather than trying to find each device/mount etc that needs to be shared with the container, e.g.
`--device=/dev/ttyUSB0 --device=/dev/ttyUSB1` etc

---

> --net=host - This option is used to make the programs inside the Docker container look like they are running on the host itself, from the perspective of the network. It allows the container greater network access than it can normally get.

The above option is also used as this seems to be a requirement for allowing bluetooth within a container.

---

So currently the container has root access which is why the special rights aren't needed.
For now I think a remark should be added however in future we should lock down the container access and those rights will then be required.

What devices use bluetooth? Is there a simple way I can test whether it's currently working?

**Comment by theyosh** [comment]
It looks bluetooth is working for me:

```
terrariumpi_1  | 2021-11-13 12:41:53,444 - INFO    - terrariumEngine       - Added new sensor miflora temperature named 'MiFlora bluetooth sensor measuring temperature' at address 'c4:7c:8d:67:11:40' to database with value 19.50C in 1.46 seconds.
terrariumpi_1  | 2021-11-13 12:41:54,214 - INFO    - terrariumEngine       - Added new sensor miflora light named 'MiFlora bluetooth sensor measuring light' at address 'c4:7c:8d:67:11:40' to database with value 136.00lux in 0.00 seconds.
terrariumpi_1  | 2021-11-13 12:41:54,221 - INFO    - terrariumEngine       - Added new sensor miflora moisture named 'MiFlora bluetooth sensor measuring moisture' at address 'c4:7c:8d:67:11:40' to database with value 61.00% in 0.01 seconds.
terrariumpi_1  | 2021-11-13 12:41:54,227 - INFO    - terrariumEngine       - Added new sensor miflora fertility named 'MiFlora bluetooth sensor measuring fertility' at address 'c4:7c:8d:67:11:40' to database with value 1249.00µS/cm in 0.01 seconds.
terrariumpi_1  | 2021-11-13 12:41:56,430 - INFO    - terrariumEngine       - Added new sensor miflora temperature named 'MiFlora bluetooth sensor measuring temperature' at address 'c4:7c:8d:66:e3:52' to database with value 19.60C in 0.34 seconds.
terrariumpi_1  | 2021-11-13 12:41:56,435 - INFO    - terrariumEngine       - Added new sensor miflora light named 'MiFlora bluetooth sensor measuring light' at address 'c4:7c:8d:66:e3:52' to database with value 174.00lux in 0.00 seconds.
terrariumpi_1  | 2021-11-13 12:41:56,439 - INFO    - terrariumEngine       - Added new sensor miflora moisture named 'MiFlora bluetooth sensor measuring moisture' at address 'c4:7c:8d:66:e3:52' to database with value 35.00% in 0.00 seconds.
terrariumpi_1  | 2021-11-13 12:41:56,443 - INFO    - terrariumEngine       - Added new sensor miflora fertility named 'MiFlora bluetooth sensor measuring fertility' at address 'c4:7c:8d:66:e3:52' to database with value 1005.00µS/cm in 0.00 seconds.
```

I am using the basic Docker compose from the suggested PR. But, as you said, the software is running root inside the container. Then it mostly will work.

**Comment by alec-pinson** [comment]
Nice this is good to know. We can look into hopefully securing the container more later.

**Comment by alec-pinson** [comment]
I will close this issue for now and open a security issue to track instead.
