### ISSUE TITLE
pigpiod

### ISSUE THREAD

**Issue by alec-pinson** [alec-pinson/TerrariumPI#7]
## As per this https://github.com/theyosh/TerrariumPI/pull/626#issuecomment-967460773

> I do miss the application pigpiod with package pigpio which is running a service/daemon which reads out some GPIO sensors.

**Comment by alec-pinson** [comment]
Can you give more info on this?

**Comment by theyosh** [comment]
Maybe I was wrong with this. As I see it is installed: https://github.com/alec-pinson/TerrariumPI/blob/4.x.y.z-docker/Dockerfile#L15
So I will look into this a bit more for we need to do some action.

**Comment by theyosh** [comment]
This is working.... I am using my develop database which almost uses all the available hardware. And it is working... So this is not an issue anymore.

**Comment by theyosh** [comment]
Unfortunately, this is not working. As the docker image is on the same network, and I left my own service running, they connected.

So we need to add the following command that should be started during startup: `pigpiod -l` before TerrariumPI (python) starts. This program will go to the background.

Could you add this to the run.sh file?

**Comment by alec-pinson** [comment]
https://github.com/alec-pinson/TerrariumPI/pull/25

added in `wkd1/test:new-slim-23` hopefully this works 👍

**Comment by theyosh** [comment]
Yes, this is now working! Thanks
